---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R controllers $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R template $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.svg $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
